[package]
name = "binance-options-client"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = "2.0"
reqwest = "0.12"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.43", features = ["full"] }
